### ISSUE TITLE
Are you still working on this?

### ISSUE THREAD

**Issue by unbiaseduser** [fieryhenry/BCGM-Python#4]
If you want to test something, just tell me. I would love to be able to mod newer versions of the game.

**Comment by unbiaseduser** [comment]
^

**Comment by fieryhenry** [comment]
Yes, I am, but atm I'm focussing my time on the save editor a bit more. This is on my list of things to do, so I will work on it again eventually

**Comment by unbiaseduser** [comment]
Alright, good to know. Hopefully I can resume my BC mod soon.
