### ISSUE TITLE
Where are unit sprites located?

### ISSUE THREAD

**Issue by Maggotson** [fieryhenry/BCGM-Python#5]
I could find sprites of approximately 10 units, but where are the others? I think we need to install and run apk for it to install everything, then modify those files.

**Comment by fieryhenry** [comment]
They are stored in the server files, the files that are downloaded when the game is first opened. If you have a rooted android device you can access them from `/data/data/jp.co.ponos.battlecatsen/files`, or if you don't from here: <https://github.com/fieryhenry/BCData/tree/master/en_server>

**Comment by Maggotson** [comment]
> [](https://github.com/fieryhenry/BCData/tree/master/en_server)

Thanks mate!
