### ISSUE TITLE
After building APK i get INSTALL_PARSE_FAILED_NO_CERTIFICATES error

### ISSUE THREAD

**Issue by Maggotson** [fieryhenry/BCGM-Python#6]
I built the apk using apktools, and tried to install it, but it resulted in an error! Any ideas how to fix that?

**Comment by fieryhenry** [comment]
you also need to sign the apk file

**Comment by Maggotson** [comment]
> you also need to sign the apk file

After signing it says "Targeting R+ requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary". I am not great in mobile development, how to fix that?

**Comment by fieryhenry** [comment]
you may need to zipalign the apk before signing. If you used jarsigner, you should use apksigner instead.

**Comment by Maggotson** [comment]
> you may need to zipalign the apk before signing. If you used jarsigner, you should use apksigner instead.

Thanks for the quick reply, I'll use apksigner!

**Comment by Maggotson** [comment]
> you may need to zipalign the apk before signing. If you used jarsigner, you should use apksigner instead.

I managed to do it!!! Thank you
